/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.perpustakaan.view;

import com.perpustakaan.model.Pengguna;
import java.awt.event.ActionEvent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class DashboardForm extends javax.swing.JFrame {

    private Pengguna pengguna;

    public DashboardForm() {
        initComponents();
        initDataPengguna();
    }

    public DashboardForm(Pengguna pengguna) {
        this();
        setPengguna(pengguna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnDashboard = new javax.swing.JMenu();
        mnData = new javax.swing.JMenu();
        mnPerson = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenuItem();
        mnSession = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DASBOARD KAS");

        lblStatus.setText("Selamat Datang");

        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(jLabel1))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mnDashboard.setText("Dashboard");
        jMenuBar1.add(mnDashboard);

        mnData.setText("Data");

        mnPerson.setText("Person");
        mnPerson.addActionListener(this::mnPersonActionPerformed);
        mnData.add(mnPerson);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addActionListener(this::mnTransaksiActionPerformed);
        mnData.add(mnTransaksi);

        mnLaporan.setText("Laporan Kas");
        mnLaporan.addActionListener(this::mnLaporanActionPerformed);
        mnData.add(mnLaporan);

        jMenuBar1.add(mnData);

        mnSession.setText("Session");

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(this::mnKeluarActionPerformed);
        mnSession.add(mnKeluar);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(this::mnLogoutActionPerformed);
        mnSession.add(mnLogout);

        jMenuBar1.add(mnSession);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        onKeluar(evt);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        onLogout(evt);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPersonActionPerformed
        onOpenPerson(evt);
    }//GEN-LAST:event_mnPersonActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        onOpenTransaksi(evt);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void mnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanActionPerformed
        onOpenLaporan(evt);
    }//GEN-LAST:event_mnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    private void initDataPengguna() {
        if (pengguna == null) {
            lblStatus.setText("Selamat datang.");
            return;
        }

        lblStatus.setText("Login sebagai: " + pengguna.getNamaLengkap() + " (" + pengguna.getRole() + ")");
    }

    public void setPengguna(Pengguna pengguna) {
        this.pengguna = pengguna;
        initDataPengguna();
    }

    // SOLUSI: Mengubah BukuForm menjadi TransaksiForm agar sesuai dengan konteks aplikasi Kas
    private void onOpenTransaksi(ActionEvent event) {
        closeAllInternalFrames();
        
        TransaksiForm transaksiForm = findOpenTransaksiForm();
        if (transaksiForm == null) {
            transaksiForm = new TransaksiForm();
            desktopPane.add(transaksiForm);
            transaksiForm.setVisible(true);
        }

        try {
            transaksiForm.setIcon(false);
            transaksiForm.setSelected(true);
            transaksiForm.toFront();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Form transaksi gagal dibuka: " + e.getMessage());
        }
    }
    
    private void onOpenPerson(ActionEvent event) {
        closeAllInternalFrames();
        
        PersonForm personForm = findOpenPersonForm();
        if (personForm == null) {
            personForm = new PersonForm();
            desktopPane.add(personForm);
            personForm.setVisible(true);
        }

        try {
            personForm.setIcon(false);
            personForm.setSelected(true);
            personForm.toFront();
        } catch (Exception e) {
            // Perbaikan Typo Pesan Dialog
            JOptionPane.showMessageDialog(this, "Form person gagal dibuka: " + e.getMessage());
        }
    }
    
    private void onOpenLaporan(java.awt.event.ActionEvent event) {
        closeAllInternalFrames();
        
        LaporanKasForm laporanForm = findOpenLaporanForm();
        if (laporanForm == null) {
            laporanForm = new LaporanKasForm();
            desktopPane.add(laporanForm);
            laporanForm.setVisible(true);
        }
        try {
            laporanForm.setSelected(true);
            laporanForm.toFront();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka laporan: " + e.getMessage());
        }
    }

    // SOLUSI: Mengubah pencarian ke TransaksiForm
    private TransaksiForm findOpenTransaksiForm() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof TransaksiForm && !frame.isClosed()) {
                return (TransaksiForm) frame;
            }
        }
        return null;
    }
    
    private PersonForm findOpenPersonForm() {
        // SOLUSI UTAMA: Mengubah tipe data loop dari JFrame menjadi JInternalFrame
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof PersonForm && !frame.isClosed()) {
                return (PersonForm) frame;
            }
        }
        return null;
    }
    
    private LaporanKasForm findOpenLaporanForm() {
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
            if (frame instanceof LaporanKasForm && !frame.isClosed()) {
                return (LaporanKasForm) frame;
            }
        }
        return null;
    }

    private void onLogout(ActionEvent event) {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin logout?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            dispose();
        }
    }

    private void onKeluar(ActionEvent event) {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Tutup aplikasi sekarang?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }
    
    private void closeAllInternalFrames() {
        // Melakukan perulangan untuk mengambil semua form yang ada di desktopPane
        for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
            // Menutup dan menghancurkan form dari memori agar bersih
            frame.dispose(); 
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            // SOLUSI: Mengganti variabel logger yang tidak terdefinisi dengan Logger bawaan Java
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu mnDashboard;
    private javax.swing.JMenu mnData;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLaporan;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnPerson;
    private javax.swing.JMenu mnSession;
    private javax.swing.JMenuItem mnTransaksi;
    // End of variables declaration//GEN-END:variables
}
