/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.perpustakaan.view;

import com.perpustakaan.config.DatabaseConnection;
import com.perpustakaan.dao.TransaksiDAO;
import com.perpustakaan.model.Transaksi;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class TransaksiForm extends javax.swing.JInternalFrame {

    private final TransaksiDAO transaksiDAO = new TransaksiDAO();
    private DefaultTableModel tableModel;
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private final DecimalFormat currencyFormat = new DecimalFormat("#,##0.00");

    // Kelas internal untuk manajemen key-value pair pada JComboBox
    private static class ComboItem {
        private final int id;
        private final String display;

        public ComboItem(int id, String display) {
            this.id = id;
            this.display = display;
        }

        public int getId() { return id; }
        @Override
        public String toString() { return display; }
    }

    public TransaksiForm() {
        initComponents();
        
        if (java.beans.Beans.isDesignTime()) {
            return;
        }

        initTableModel();
        initListeners();
        loadComboPerson();
        loadComboJenis();
        loadDataTable();
        resetForm();
    }

    private void loadComboPerson() {
        cmbPerson.removeAllItems();
        cmbPerson.addItem(new ComboItem(0, "--- Umum / Tanpa Person ---"));
        String sql = "SELECT id_person, nama FROM person ORDER BY nama";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                cmbPerson.addItem(new ComboItem(rs.getInt("id_person"), rs.getString("nama")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data Person: " + e.getMessage());
        }
    }

    private void loadComboJenis() {
        cmbJenisTransaksi.removeAllItems();
        String sql = "SELECT id_jenis, nama_jenis FROM jenis_transaksi ORDER BY id_jenis";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                cmbJenisTransaksi.addItem(new ComboItem(rs.getInt("id_jenis"), rs.getString("nama_jenis")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data Jenis Transaksi: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTransaksi = new javax.swing.JLabel();
        lblPerson = new javax.swing.JLabel();
        cmbPerson = new javax.swing.JComboBox<>();
        lblJenisTransaksi = new javax.swing.JLabel();
        cmbJenisTransaksi = new javax.swing.JComboBox<>();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblKeterangan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblDataTransaksi = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataTransaksi = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        lblIdTransaksi = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTransaksi.setText("Transaksi");

        lblPerson.setText("Person");

        lblJenisTransaksi.setText("Jenis Transaksi");

        lblJumlah.setText("Jumlah ");

        lblKeterangan.setText("Keterangan");

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane1.setViewportView(txtKeterangan);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        lblDataTransaksi.setText("Data Transaksi");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        tblDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Person", "Jenis", "Jumlah", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDataTransaksi);
        if (tblDataTransaksi.getColumnModel().getColumnCount() > 0) {
            tblDataTransaksi.getColumnModel().getColumn(0).setMinWidth(40);
            tblDataTransaksi.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblDataTransaksi.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        lblCari.setText("Cari");

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        lblIdTransaksi.setText("Id Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblJenisTransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerson, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeterangan, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtJumlah)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbJenisTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDataTransaksi)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnReset)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEdit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnHapus)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblTransaksi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdTransaksi)
                        .addGap(33, 33, 33)
                        .addComponent(txtIdTransaksi)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdTransaksi)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerson)
                    .addComponent(cmbPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisTransaksi)
                    .addComponent(cmbJenisTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKeterangan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnReset)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(lblDataTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        onSimpan(evt);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        onReset(evt);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        onEdit(evt);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        onHapus(evt);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        onCari(evt);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        onRefresh(evt);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    private void initTableModel() {
        tableModel = new DefaultTableModel(new String[]{"ID", "Tanggal", "Person", "Jenis", "Jumlah", "Keterangan"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tblDataTransaksi.setModel(tableModel);
        tblDataTransaksi.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void initListeners() {
        tblDataTransaksi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { showSelectedDataToForm(); }
        });
    }

    private void onSimpan(ActionEvent evt) {
        Transaksi t = getTransaksiFromForm();
        if (t == null) return;

        t.setTanggal(new Date()); // Menetapkan waktu sistem saat ini secara otomatis
        if (transaksiDAO.insert(t)) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan.");
            refreshTableAfterCrud();
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onEdit(ActionEvent evt) {
        Transaksi t = getTransaksiFromForm();
        if (t == null) return;

        if (transaksiDAO.update(t)) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil diubah.");
            refreshTableAfterCrud();
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengubah transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void onHapus(ActionEvent evt) {
        String idText = txtIdTransaksi.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data transaksi yang akan dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus transaksi ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(idText);
            if (transaksiDAO.delete(id)) {
                JOptionPane.showMessageDialog(this, "Transaksi berhasil dihapus.");
                refreshTableAfterCrud();
                resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void onReset(ActionEvent evt) {
        resetForm();
        loadDataTable();
    }

    private void onRefresh(ActionEvent evt) {
        txtCari.setText("");
        loadComboPerson();
        loadComboJenis();
        loadDataTable();
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
    }

    private void onCari(ActionEvent evt) {
        String keyword = txtCari.getText().trim();
        if (keyword.isEmpty()) {
            loadDataTable();
            return;
        }
        List<Transaksi> list = transaksiDAO.search(keyword);
        setTableRows(list);
    }

    private Transaksi getTransaksiFromForm() {
        String idText = txtIdTransaksi.getText().trim();
        String jumlahText = txtJumlah.getText().trim();
        String keterangan = txtKeterangan.getText().trim();

        if (jumlahText.isEmpty() || keterangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Field Jumlah dan Keterangan wajib diisi.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        double jumlah;
        try {
            jumlah = Double.parseDouble(jumlahText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        if (jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah nilai transaksi harus lebih dari 0.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        ComboItem personItem = (ComboItem) cmbPerson.getSelectedItem();
        ComboItem jenisItem = (ComboItem) cmbJenisTransaksi.getSelectedItem();

        if (jenisItem == null) {
            JOptionPane.showMessageDialog(this, "Jenis transaksi wajib dipilih.", "Validasi", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        int idTransaksi = idText.isEmpty() ? 0 : Integer.parseInt(idText);
        Integer idPerson = (personItem == null || personItem.getId() == 0) ? null : personItem.getId();

        Transaksi t = new Transaksi();
        t.setIdTransaksi(idTransaksi);
        t.setIdPerson(idPerson);
        t.setIdJenis(jenisItem.getId());
        t.setJumlah(jumlah);
        t.setKeterangan(keterangan);
        return t;
    }

    private void loadDataTable() {
        List<Transaksi> list = transaksiDAO.getAll();
        setTableRows(list);
    }

    private void setTableRows(List<Transaksi> list) {
        tableModel.setRowCount(0);
        for (Transaksi t : list) {
            tableModel.addRow(new Object[]{
                t.getIdTransaksi(),
                dateFormat.format(t.getTanggal()),
                t.getNamaPerson(),
                t.getNamaJenis(),
                currencyFormat.format(t.getJumlah()),
                t.getKeterangan()
            });
        }
    }

    private void showSelectedDataToForm() {
        int selectedRow = tblDataTransaksi.getSelectedRow();
        if (selectedRow == -1) return;

        txtIdTransaksi.setText(tableModel.getValueAt(selectedRow, 0).toString());
        
        // Parsing nominal uang dari string berformat rupiah kembali ke tipe double mentah
        try {
            Number num = currencyFormat.parse(tableModel.getValueAt(selectedRow, 4).toString());
            txtJumlah.setText(String.valueOf(num.doubleValue()));
        } catch (Exception e) {
            txtJumlah.setText("");
        }
        
        txtKeterangan.setText(tableModel.getValueAt(selectedRow, 5).toString());

        // Mensinkronkan ComboBox Visual berdasarkan nama relasi di tabel
        String namaPersonTable = tableModel.getValueAt(selectedRow, 2).toString();
        for (int i = 0; i < cmbPerson.getItemCount(); i++) {
            if (cmbPerson.getItemAt(i).toString().equals(namaPersonTable)) {
                cmbPerson.setSelectedIndex(i);
                break;
            }
        }

        String namaJenisTable = tableModel.getValueAt(selectedRow, 3).toString();
        for (int i = 0; i < cmbJenisTransaksi.getItemCount(); i++) {
            if (cmbJenisTransaksi.getItemAt(i).toString().equals(namaJenisTable)) {
                cmbJenisTransaksi.setSelectedIndex(i);
                break;
            }
        }
    }

    private void refreshTableAfterCrud() {
        String keyword = txtCari.getText().trim();
        if (keyword.isEmpty()) {
            loadDataTable();
        } else {
            List<Transaksi> list = transaksiDAO.search(keyword);
            setTableRows(list);
        }
    }

    private void resetForm() {
        txtIdTransaksi.setText(transaksiDAO.getNextId());
        txtJumlah.setText("");
        txtKeterangan.setText("");
        if (cmbPerson.getItemCount() > 0) cmbPerson.setSelectedIndex(0);
        if (cmbJenisTransaksi.getItemCount() > 0) cmbJenisTransaksi.setSelectedIndex(0);
        cmbPerson.requestFocus();
        tblDataTransaksi.clearSelection();
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new TransaksiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<Object> cmbJenisTransaksi;
    private javax.swing.JComboBox<Object> cmbPerson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblDataTransaksi;
    private javax.swing.JLabel lblIdTransaksi;
    private javax.swing.JLabel lblJenisTransaksi;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JLabel lblTransaksi;
    private javax.swing.JTable tblDataTransaksi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextArea txtKeterangan;
    // End of variables declaration//GEN-END:variables
}
